# openapi-definition.yaml
swagger: "2.0"
info:
  title: my-api
  description: Serverless APIs with API Gateway
  version: 1.0.0
schemes:
 - https
produces:
 - application/json
securityDefinitions:
 api_key:
    type: "apiKey"
    name: "key"
    in: "query"
paths:
  /process:
      post:
        security:
          - api_key: []
        summary: Process Data
        operationId: process_data
        x-google-backend:
          address: https://us-central1-project-tomy-mati.cloudfunctions.net/function-test
          protocol: h2
        responses:
          '200':
            description: A successful response
            schema:
              type: string